sort:
  max_age: 50  # Maximum number of frames to keep alive a track without associated detections.
  min_hits: 3   # Minimum number of associated detections before track is initialised.
  iou_threshold: 0.3  # Minimum IOU for match.
